//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace myshop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int 商品編號 { get; set; }
        public string 商品名稱 { get; set; }
        public string 商品類別 { get; set; }
        public Nullable<int> 類別編號 { get; set; }
        public System.DateTime 製造日期 { get; set; }
        public string 商品描述 { get; set; }
        public decimal 價格 { get; set; }
        public bool 是否庫存 { get; set; }
        public string 商品圖 { get; set; }
    }
}
